#!/bin/bash

# My IEP Hero - Play Console Upload Helper Script
# Provides guidance and automation for uploading AAB to Play Console

set -e

echo "🚀 My IEP Hero - Play Console Upload Guide"
echo "========================================"

# Configuration
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/dist/android"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

# Find latest AAB file
LATEST_AAB=$(find "$OUTPUT_DIR" -name "MyIEPHero-*.aab" -type f -exec ls -t {} + | head -1)

if [ -z "$LATEST_AAB" ]; then
    log_warning "No AAB files found in $OUTPUT_DIR"
    echo "Please build AAB first:"
    echo "  scripts/android/build-aab.sh"
    exit 1
fi

log_info "Latest AAB found: $(basename "$LATEST_AAB")"

echo ""
echo "📋 Play Console Upload Checklist"
echo "================================"
echo ""

# Pre-upload checklist
echo "🔍 Pre-Upload Verification:"
echo "   □ AAB file generated: ✅ $(basename "$LATEST_AAB")"
echo "   □ File size: $(ls -lh "$LATEST_AAB" | awk '{print $5}')"

# Check if keystore was used
if grep -q "debug" "$LATEST_AAB" 2>/dev/null; then
    log_warning "   □ Signing: DEBUG KEYSTORE DETECTED!"
    echo "     ⚠️  This AAB appears to be signed with debug keystore"
    echo "     ⚠️  For production, regenerate with production keystore"
else
    log_success "   □ Signing: Production keystore (assumed)"
fi

echo ""
echo "🏪 Play Console Setup Steps:"
echo "============================"
echo ""
echo "1. 📝 Create Play Console Account (if needed):"
echo "   • Go to: https://play.google.com/console"
echo "   • Sign in with Google account"
echo "   • Pay \$25 one-time developer registration fee"
echo ""

echo "2. 🆕 Create New App:"
echo "   • Click 'Create app'"
echo "   • App name: My IEP Hero"
echo "   • Default language: English"
echo "   • App or game: App"
echo "   • Free or paid: Free"
echo "   • Privacy Policy: Required for educational apps"
echo ""

echo "3. 📱 App Setup:"
echo "   • Main store listing:"
echo "     - App name: My IEP Hero"
echo "     - Short description: IEP advocacy and special education support"
echo "     - Full description: Educational advocacy platform for IEP management"
echo "     - Category: Education"
echo "     - Content rating: Everyone (ESRB E)"
echo ""

echo "4. 🔧 App Content:"
echo "   • Content rating questionnaire:"
echo "     - Educational content: Yes"
echo "     - Target age: All ages"
echo "     - Data collection: Declare if applicable"
echo ""

echo "5. 📤 Upload AAB:"
echo "   • Go to 'Release' > 'Testing' > 'Internal testing'"
echo "   • Create new release"
echo "   • Upload AAB: $LATEST_AAB"
echo "   • Add release notes"
echo "   • Set version name and rollout percentage"
echo ""

echo "6. 👥 Configure Internal Testing:"
echo "   • Add internal testers (email addresses)"
echo "   • Create testing groups if needed"
echo "   • Generate shareable link for testers"
echo ""

echo "7. 🚀 Publish to Internal Track:"
echo "   • Review all sections"
echo "   • Submit for review"
echo "   • Wait for processing (usually 1-3 hours)"
echo ""

echo "📞 Commands for this AAB:"
echo "========================"
echo ""
echo "# Open Play Console:"
echo "open https://play.google.com/console"
echo ""
echo "# Verify AAB locally (if bundletool installed):"
echo "bundletool validate --bundle=\"$LATEST_AAB\""
echo ""
echo "# Generate universal APK for testing (if bundletool installed):"
echo "bundletool build-apks --bundle=\"$LATEST_AAB\" --output=\"${LATEST_AAB%.aab}.apks\" --mode=universal"
echo ""

echo "🎯 Internal Testing URLs:"
echo "========================="
echo "After publishing to internal track, testers can access:"
echo "• Testing link: [Generated by Play Console]"
echo "• Play Store link: https://play.google.com/store/apps/details?id=com.myiephero.app"
echo ""

echo "⏰ Timeline Expectations:"
echo "========================"
echo "• AAB upload and processing: 1-3 hours"
echo "• Internal testing availability: Immediate after processing"
echo "• Closed testing track: Up to 24 hours"
echo "• Production review: 7 days (typical)"
echo ""

echo "🔗 Useful Links:"
echo "================="
echo "• Play Console: https://play.google.com/console"
echo "• Developer Policy: https://play.google.com/about/developer-content-policy/"
echo "• AAB Documentation: https://developer.android.com/guide/app-bundle"
echo "• Bundletool: https://github.com/google/bundletool/releases"
echo ""

log_success "Upload guide complete! 🎉"
echo "Follow the steps above to upload your AAB to Play Console internal testing."